spring.application.name=tarea

#HABILITAMOS CONSOLA WEB
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#CONFIGURAMOS URL DE BASE DE DATOS EN MEMORIA
spring.datasource.url=jdbc:h2:mem:tareadb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
